// api/vuejs/src/components/User.vue
<template>
   <div class="columns is-mobile is-centered">
            <div class="column is-half">

               <div class="card user">
                  <div class="card-content">
                     <div class="media">
                        <div class="media-left">
                           <figure class="image is-48x48">
                              <img :src="user.avatar_url" alt="Placeholder image"/>
                           </figure>
                        </div>
                        <div class="media-content">
                           <p class="title is-4">{{this.user.name || this.user.login}}</p>
                           <p class="subtitle is-6">@{{this.user.login}}</p>
                        </div>
                     </div>

                     <div class="content">
                        <span>{{this.user.created_at !== undefined ? this.user.created_at.split("T")[0] : ""}}</span>
                        <br/>
                        <br/>
                        {{this.user.bio}}
                     </div>
                  </div>
               </div>

            </div>
         </div>
</template>

<script>
export default {
   name: "User",
   data() {
      return {
         user: []
      }
   },
   beforeMount() {
      fetch(`https://api.github.com/users/${this.$route.params.user}`)
      .then(result => result.json())
      .then(response => {
         this.user = response
      })
   }
}
</script>


<style>
.user{
   margin-top: 50px;
   margin-bottom: 50px;
}
</style>

// api/react/src/Components/User/User.js
import React from "react"
import "./user.css"

export default class User extends React.Component {

   constructor(){
      super()
      this.state = {
         user: []
      }
   }

   componentWillMount() {
      fetch(`https://api.github.com/users/${this.props.match.params.user}`)
      .then(result => result.json())
      .then(response => {
         this.setState({ user: response }, () => {
            console.log(this.state.user)
         })
      })
   }

   render() {
      return (


         <div className="columns is-mobile is-centered">
            <div className="column is-half">

               <div className="card user">
                  <div className="card-content">
                     <div className="media">
                        <div className="media-left">
                           <figure className="image is-48x48">
                              <img src={this.state.user.avatar_url} alt="Placeholder image"/>
                           </figure>
                        </div>
                        <div className="media-content">
                           <p className="title is-4">{this.state.user.name || this.state.user.login}</p>
                           <p className="subtitle is-6">@{this.state.user.login}</p>
                        </div>
                     </div>

                     <div className="content">
                        {this.state.user.created_at !== undefined ? <span>{this.state.user.created_at.split("T")[0]}</span> : <span></span>}
                        <br/>
                        <br/>
                        {this.state.user.bio}
                     </div>
                  </div>
               </div>

            </div>
         </div>

      )
   }
}
