// api/svelte/src/components/App.svelte
<script>
	import { Router, Link, Route } from "svelte-routing";
	import NavBar from "./NavBar.svelte"
	import Homepage from "./Homepage.svelte"
	import User from "./User.svelte"
	import ListeUsers from "./ListeUsers.svelte"
	import Footer from "./Footer.svelte"
	export let url = ""
</script>

<main>

<Router url="{url}">
  	<NavBar/>
  	<div>
		<Route path="/users" component="{ListeUsers}"/>
		<Route path="/user/:user" let:params>
			<User id="{params.user}"/>
	 	</Route>
    	<Route path="/" component="{Homepage}"/>
  	</div>
	<Footer/>
</Router>

</main>

<style>

</style>

// api/react/src/Components/App.js
import React from 'react';
import Navbar from "./Navbar/Navbar"
import { BrowserRouter as Router, Route, Switch } from "react-router-dom"
import Home from "./Home/Home"
import ListUsers from "./ListUsers/ListUsers"
import User from "./User/User"
import Footer from './Footer/Footer';

function App() {
  return (
    <div>
      <Router>
        
        <Navbar/>

        <Switch>
          <Route exact path="/" component={Home}/>
          <Route exact path="/users" component={ListUsers}/>
          <Route path="/user/:user" component={User}/>
        </Switch>

        <Footer/>

      </Router>
    </div>
    
    
  );
}

export default App;
