// api/react/src/Components/Home/Home.js
import React from "react"
import "./home.css"
import { Link } from "react-router-dom"

export default class Home extends React.Component {
   render() {
      return (
         <section className="hero is-success is-bold is-medium">
            <div className="hero-body">
               <div className="container has-text-centered">
                  <h1 className="title">
                     React application
                  </h1>
                  <div className="subtitle has-text-centered">
                     <Link className="button is-white" to="/users">List of users</Link>
                     <Link className="button is-white" to="/user/MrAnyx">My info</Link>
                  </div>
               </div>
            </div>
         </section>
      )
   }
}

// api/angular/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  template: `
    <section class="hero is-success is-bold is-medium">
      <div class="hero-body">
          <div class="container has-text-centered">
            <h1 class="title">
                React application
            </h1>
            <div class="subtitle has-text-centered">
                <a class="button is-white" routerLink="users">List of users</a>
                <a class="button is-white" routerLink="users/MrAnyx">My info</a>
            </div>
          </div>
      </div>
    </section>
  `,
  styles: [`
    .button {
      margin: 20px 10px;
    }
  `]
})
export class HomeComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
