// api/vuejs/src/components/NavBar.vue
<template>
    <nav class="navbar is-dark">
      <div class="navbar-brand">
         <router-link class="navbar-item" :to="{name: 'home'}">
            <img src="../assets/logo.png"/>
         </router-link>
      </div>
   </nav>
</template>

<script>

export default {
   name: "NavBar"
}
</script>


<style>

</style>

// api/react/src/Components/Navbar/Navbar.js
import React from "react"
import { Link } from "react-router-dom"
import "./navbar.css"
import image from "../../assets/images/logo.png"

export default class Navbar extends React.Component {
   render() {
      return (

         <nav className="navbar is-dark">
            <div className="navbar-brand">
               <Link className="navbar-item" to="/">
                  <img src={image}/>
               </Link>
            </div>
         </nav>
      )
   }
}
