// api/react/src/Components/Footer/Footer.js
import React from "react"

export default class Footer extends React.Component {
   render() {
      return (
         <footer className="footer">
            <div className="content has-text-centered">
               <p>
                  Made with 💕 by MrAnyx
               </p>
            </div>
         </footer>
      )
   }
}

// api/angular/src/app/components/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-footer',
  template: `
    <!-- footer -->
    <footer class="footer">
      <div class="container">
        <div class="content has-text-centered">
          <p>
            Made with 💕 by MrAnyx
          </p>
        </div>
      </div>
    </footer>
  `,
  styles: []
})
export class FooterComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
