// api/svelte/src/components/NavBar.svelte
<script>
import { Link } from "svelte-routing"
import src from "../../public/assets/logo.png"
</script>

<main>

<nav class="navbar is-dark">
   <div class="navbar-brand">
      <a class="navbar-item" href="/" replace>
         <img {src} alt="navbar logo"/>
      </a>
   </div>
</nav>

</main>

<style>

</style>

// api/vuejs/src/components/NavBar.vue
<template>
    <nav class="navbar is-dark">
      <div class="navbar-brand">
         <router-link class="navbar-item" :to="{name: 'home'}">
            <img src="../assets/logo.png"/>
         </router-link>
      </div>
   </nav>
</template>

<script>

export default {
   name: "NavBar"
}
</script>


<style>

</style>
