// vuejs/src/App.vue
<template>
	<div id="app">
		<NavBar/>
		<router-view/>
	</div>
</template>

<script>
import NavBar from "./components/NavBar.vue"

export default {
	components: {
		NavBar
	}
}
</script>

<style>
/* Import font product sans */
@font-face {
	font-family: ProductSans;
	src: url("./assets/ProductSans-Regular.ttf");
}

/* Reset Style */
*{
	margin: 0px;
	padding: 0px;
	font-family: ProductSans;
	box-sizing: border-box;
	vertical-align: middle;
}

body, html{
	margin: 0;
	width: 100%;
	height: 100%;
}
</style>

// non-api/svelte/src/components/App.svelte
<!-- App.svelte -->
<script>
  import { Router, Link, Route } from "svelte-routing";
  import NavBar from "./NavBar.svelte"
  import Homepage from "./Homepage.svelte"
  import Content from "./Content.svelte"

  export let url = "";
</script>

<Router url="{url}">
  <NavBar/>
  <div>
    <Route path="/:page" component="{Content}" />
    <Route path="/" component="{Homepage}"/>
  </div>
</Router>


<style>

@font-face {
	font-family: ProductSans;
	src: url("./assets/ProductSans-Regular.ttf");
}

:global(body){
	margin: 0px;
	padding: 0px;
	font-family: ProductSans;
	box-sizing: border-box;
	vertical-align: middle;
}
</style>
